version: "3.8"

services:
  # image project
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: app-php
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - app-php

  # nginx
  nginx:
    image: nginx:alpine
    ports:
      - "8990:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-php

networks:
  app-php:
    driver: bridge
